sonar.projectKey=gestor-cursos-react
sonar.projectName=Gestor Cursos React
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_1dddcaf57fc310c1ee4553a1a99cf68cc4e9fe14